### ISSUE TITLE
DB search fails with "AttributeError: globalvars instance has no attribute 'installdir'

### ISSUE THREAD

**Issue by asteeves** [hjkgrp/molSimplify#10]
DBsearch fails from GUI and from command line:
```
************************************************************
******** Welcome to molSimplify! Let's get started. ********
************************************************************


Traceback (most recent call last):
  File "/Users/asteeves/anaconda/envs/test-env/bin/molsimplify", line 11, in <module>
    load_entry_point('molSimplify', 'console_scripts', 'molsimplify')()
  File "/Users/asteeves/Documents/molSimplify/molSimplify/__main__.py", line 72, in main
    emsg = startgen(sys.argv,False,gui)
  File "/Users/asteeves/Documents/molSimplify/molSimplify/Scripts/generator.py", line 114, in startgen
    emsg = dbsearch(rundir,args,globs)
  File "/Users/asteeves/Documents/molSimplify/molSimplify/Scripts/dbinteract.py", line 360, in dbsearch
    print(globs.installdir)
AttributeError: globalvars instance has no attribute 'installdir'
```

**Comment by asteeves** [comment]
Fixed by commit https://github.com/hjkgrp/molSimplify/commit/dc0c732cd94d6399c41c77ca1db0fa41107f5583
