### ISSUE TITLE
DB search with SMARTS pattern fails due to splitting on comma

### ISSUE THREAD

**Issue by asteeves** [hjkgrp/molSimplify#11]
Both from GUI and from command line, trying to search a database with the smarts pattern from Tutorial 4 ([#7D1,#7D2;!+]) fails with a SMARTS error in Open Babel:
```
(test-env)  [asteeves  @ ahsmbp:~/Runs]$ molsimplify -i dbsearch.in 
main_invoked

************************************************************
******** Welcome to molSimplify! Let's get started. ********
************************************************************


[#7D1
ligdb fastsearch database file missing from ChemDB/. Please make sure file ligdb.fs is there, it speeds up search significantly..
ligdb fastsearch database file missing from ChemDB/. Please make sure file ligdb.fs is there, it speeds up search significantly..
Performing substructure search:
==============================
*** Open Babel Error  in SMARTSError
  SMARTS Error:
[#7D1
     ^

==============================
*** Open Babel Error  in Do
  [#7D1 cannot be interpreted as either valid SMARTS or the name of a file with an extension known to OpenBabel that contains one or more pattern molecules.
0 molecules converted
2 errors 11 audit log messages 

Applying filters:
0 molecules converted
8 audit log messages 

Stripping salts and removing duplicates
0 molecules converted

Filtering by allowed elements:
Element filter returns 0 results
==============================
*** Open Babel Error  in SMARTSError
  SMARTS Error:
[#7D1
     ^

Traceback (most recent call last):
  File "/Users/asteeves/anaconda/envs/test-env/bin/molsimplify", line 11, in <module>
    load_entry_point('molSimplify', 'console_scripts', 'molsimplify')()
  File "/Users/asteeves/Documents/molSimplify/molSimplify/__main__.py", line 72, in main
    emsg = startgen(sys.argv,False,gui)
  File "/Users/asteeves/Documents/molSimplify/molSimplify/Scripts/generator.py", line 114, in startgen
    emsg = dbsearch(rundir,args,globs)
  File "/Users/asteeves/Documents/molSimplify/molSimplify/Scripts/dbinteract.py", line 480, in dbsearch
    flag = matchsmarts(smistr,outf,catoms,nres)
  File "/Users/asteeves/Documents/molSimplify/molSimplify/Scripts/dbinteract.py", line 318, in matchsmarts
    sm = pybel.Smarts(smarts)
  File "/Users/asteeves/anaconda/envs/test-env/lib/python2.7/site-packages/pybel.py", line 912, in __init__
    raise IOError("Invalid SMARTS pattern")
IOError: Invalid SMARTS pattern
```

**Comment by asteeves** [comment]
Closed by https://github.com/hjkgrp/molSimplify/commit/95a998666d5d95a066400e705de09cb7fa164141
