### ISSUE TITLE
Problem w/ tutorial 4: "Globalvars instance has no attribute 'installdir' "

### ISSUE THREAD

**Issue by mrauha** [hjkgrp/molSimplify#12]
Hello!

First of all, your software is  looks really amazing and fits my research interests.

I installed molSimplify using conda. I'm trying out the [tutorial 4](http://hjkgrp.mit.edu/content/molsimplify-tutorial-4-database-searching), but I'm getting the following error 

```
$molsimplify -i ex1.in 
main_invoked

************************************************************
******** Welcome to molSimplify! Let's get started. ********
************************************************************


Traceback (most recent call last):
  File "/home/markus/anaconda2/envs/molSimplify/bin/molsimplify", line 11, in <module>
    load_entry_point('molSimplify==1.2.6a0', 'console_scripts', 'molsimplify')()
  File "/home/markus/anaconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/__main__.py", line 69, in main
    emsg = startgen(sys.argv,False,gui)
  File "/home/markus/anaconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/Scripts/generator.py", line 114, in startgen
    emsg = dbsearch(rundir,args,globs)
  File "/home/markus/anaconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/Scripts/dbinteract.py", line 360, in dbsearch
    print(globs.installdir)
AttributeError: globalvars instance has no attribute 'installdir'
```

with ex1.in being

```
-dbcatoms 1 # index of connecting atom in SMARTS query, see below
-dbbase chembl_22_1 # name of your database file without the file extension
-dbfs yes
-dbfname simres.smi # results file name, default is simres.smi
-dbatoms <15 # atom filter
-dbsmarts [#7D1,#7D2;!+]
-dballowedels H,C,N,F,Cl,Br,I # allowed element filter
-dbmaxsmartsmatches 1 # max. SMARTS matches filter
```

I read the manual and it mentioned that INSTALLDIR should be set to "the installation directory (top directory) of the program where all the supporting files are located". I set my ~/.molSimplify to
`INSTALLDIR=/home/markus/anaconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify
`
but it didn't work.

Any tips on solving this problem?

Best regards,
Markus

**Comment by asteeves** [comment]
We recently changed the way these files were being accessed so the path should not need to be set manually. Could you try downloading a current version, either from the GitHub or via Conda and let us know if the problem still exists?

**Comment by jpjanet** [comment]
Closing due to inactivity
