### ISSUE TITLE
dictionary lookup problem for some elements (Pb?)

### ISSUE THREAD

**Issue by chrisewolf** [hjkgrp/molSimplify#13]
It seems the supercell builder has a problem looking up certain elements such as Pb.

the error message in the console would be

`We didn't find the atomic mass of Pb in the dictionary. Assigning default value of 12!`

QE input subsequently fails (xyz seems to be written properly though)

```
final cell vector, inc vapour space is :
[[4.93, 0, 0], [0, 4.9299999999999997, 0], [0, 0, 24.93]]
Traceback (most recent call last):
  File "/home/chris/miniconda2/envs/molSimplify/bin/molsimplify", line 11, in <module>
    load_entry_point('molSimplify==1.2.6a0', 'console_scripts', 'molsimplify')()
  File "/home/chris/miniconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/__main__.py", line 78, in main
    emsg = startgen(args,False,gui)
  File "/home/chris/miniconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/Scripts/generator.py", line 144, in startgen
    emsg = slab_module_supervisor(args,rundir)
  File "/home/chris/miniconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/Scripts/cellbuilder.py", line 1389, in slab_module_supervisor
    write_periodic_mol3d_to_qe(super_cell,new_dup_vector,rootdir + 'slab/slab.in')
  File "/home/chris/miniconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/Scripts/periodic_QE.py", line 70, in write_periodic_mol3d_to_qe
    f.write(str(elements) + "    " +  str(globs.amass()[elements][0])  + "     " + ps_info + '\n')
KeyError: 'Pb'

```

**Comment by chrisewolf** [comment]
Ok, the solution is simple; the dictionary in  globalvars.py simply doesn't cover the entire PSE so entering the desired atoms into  amassdict does the trick!

**Comment by jpjanet** [comment]
Closed by user.
