### ISSUE TITLE
NameError: global name 'ligloc' is not defined

### ISSUE THREAD

**Issue by mrauha** [hjkgrp/molSimplify#17]
I'm having some problems with molsimplify's cli. I followed the installation instructions of the user guide:
```
conda create -n mols2 python=2.7
conda activate mols2
conda install -c hjkgroup molSimplify
conda install -c dsdale24 pyqt5
```
After which I ran

`molsimplify -core Fe -lig water -ligocc`

Which gives

```
No input file detected, reading arguments from commandline
molSimplify is starting!

************************************************************
******** Welcome to molSimplify! Let's get started. ********
************************************************************


Checking input...
WARNING: No oxidation state specified. Defaulting to 2
WARNING: No spin multiplicity specified. Defaulting to 5
Please check this against our ANN output (where available)
Traceback (most recent call last):
  File "/home/markus/anaconda3/envs/mols2/bin/molsimplify", line 11, in <module>
    load_entry_point('molSimplify==1.2.7a0', 'console_scripts', 'molsimplify')()
  File "/home/markus/anaconda3/envs/mols2/lib/python2.7/site-packages/molSimplify/__main__.py", line 161, in main
    emsg = startgen(args,False,gui)
  File "/home/markus/anaconda3/envs/mols2/lib/python2.7/site-packages/molSimplify/Scripts/generator.py", line 106, in startgen
    emsg = checkinput(args)
  File "/home/markus/anaconda3/envs/mols2/lib/python2.7/site-packages/molSimplify/Scripts/inparse.py", line 92, in checkinput
    if ligloc:
NameError: global name 'ligloc' is not defined
```

**Comment by jpjanet** [comment]
Thanks for pointing this out - this issue was fixed in 6325d255d3eb226f6a51f2987d227f415cfaafa7 but the anaconda image was not updated. I have updated the image and the issue should be resolved with the version 1.4.4. @mrauha you will need to update your installation, I'd recommend running (from in the conda env):

```
conda remove molsimplify
conda install -c hjkgroup molsimplify
```
 in order oder to get a clean install (or you can try `conda update`)
