### ISSUE TITLE
`pip install` missing files + `geomgroups[count]` list index out of range

### ISSUE THREAD

**Issue by fredauski** [hjkgrp/molSimplify#246]
Dear all,

I'm having some trouble getting molSimplify to run on my M3 MacBook Pro.

When I create a new Python 3.12.4 virtual environment (`pyenv virtualenv 3.12.4 molsimplify`) and install molSimplify into the venv (`pip install --upgrade pip && pip install molsimplify`), I get the following error message trying to run `molsimplify -h`:

```bash
>>> molsimplify -h

TensorFlow connection successful
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/molsimplify/bin/molsimplify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/.pyenv/versions/3.12.4/envs/molsimplify/lib/python3.12/site-packages/molSimplify/molSimplify/__main__.py", line 168, in main
    parseinputs_basic(parser)
  File "/Users/user/.pyenv/versions/3.12.4/envs/molsimplify/lib/python3.12/site-packages/molSimplify/molSimplify/Scripts/inparse.py", line 1109, in parseinputs_basic
    "-core", help="core structure with currently available: "+getcores())
                                                              ^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.4/envs/molsimplify/lib/python3.12/site-packages/molSimplify/molSimplify/Scripts/io.py", line 246, in getcores
    mcores = getmcores()
             ^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.4/envs/molsimplify/lib/python3.12/site-packages/molSimplify/molSimplify/Scripts/io.py", line 267, in getmcores
    mcores = readdict(mcores)
             ^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.4/envs/molsimplify/lib/python3.12/site-packages/molSimplify/molSimplify/Scripts/io.py", line 95, in readdict
    with open(fname, 'r') as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/.pyenv/versions/3.12.4/envs/molsimplify/lib/python3.12/site-packages/molSimplify/Cores/cores.dict'
```

This error (and the same one for `molSimplify/Data/coordinations.dict`) can be fixed by simply creating those files (`mkdir /Users/user/.pyenv/versions/3.12.4/envs/molsimplify/lib/python3.12/site-packages/molSimplify/Cores/cores.dict && touch /Users/user/.pyenv/versions/3.12.4/envs/molsimplify/lib/python3.12/site-packages/molSimplify/Cores/cores.dict`), similar to this issue #243.

I now get a new error though:

```bash
>>> molsimplify -h

TensorFlow connection successful
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/molsimplify/bin/molsimplify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/.pyenv/versions/3.12.4/envs/molsimplify/lib/python3.12/site-packages/molSimplify/__main__.py", line 168, in main
    parseinputs_basic(parser)
  File "/Users/user/.pyenv/versions/3.12.4/envs/molsimplify/lib/python3.12/site-packages/molSimplify/Scripts/inparse.py", line 1114, in parseinputs_basic
    parser.add_argument("-geometry", help=f"geometry; currently available ones are {', '.join(getgeoms()[2])} which correspond to {', '.join(getgeoms()[1])}", action="store_true")
                                                                                              ^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.4/envs/molsimplify/lib/python3.12/site-packages/molSimplify/Scripts/io.py", line 81, in getgeoms
    geomgroups[count].append(geomshorts[0])
    ~~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

I also tried downloading the repo and installing it locally (`pip install -e .`) to the same effect.

Am I missing something here?

Thanks for your help in this matter, it's greatly appreciated!

**Comment by dbkchu** [comment]
Hi @fredauski, this should be fixed in the latest image of the GitHub repo. @gianmarco-terrones fixed it with commit [20d1960](https://github.com/hjkgrp/molSimplify/commit/20d9160cfd2e7bcdabfe5e6abd2f51bd4e286809). @gianmarco-terrones, can we also update the pip deployment?

**Comment by gianmarco-terrones** [comment]
@dbkchu Sounds good, we may just release a new version of molSimplify (v1.7.5) so that the PyPi release does not throw this error.

@fredauski, thank you for bringing this to our attention. I think it makes sense that making the files prevents the FileNotFoundError, but leads to an IndexError since you used `touch` to make the files and thus they are empty even though they are present. In the meantime, you can try what was done in issue #243, where manually copying over the relevant folder and files seems to fix the issue. Alternatively, you could try installing via Conda (instructions in the repo's README) either from GitHub or from Anaconda. We are more confident that these installations should not have bugs, since these options have been around for longer, whereas we only recently included the option to install from pip.

**Comment by fredauski** [comment]
@dbkchu @gianmarco-terrones thanks for your quick reply!

I think I now understand the problem. I tried cloning the repo and installing it via the `pip install -e .` route again and this time it works! I must've messed something up trying it this way previously.

I'll be using it like this for the time being and am looking forward to the 1.7.5 release 👍 

Thanks again for your time
