### ISSUE TITLE
Include PyYAML in Conda dependencies

### ISSUE THREAD

**Issue by amlimaye** [hjkgrp/molSimplify#25]
Hi,

A small issue: when I create a new conda environment and install molSimplify using the instructions on the website, I get an error with finding the yaml module.

```
$ conda create -nmstest python=2.7
...
$ conda activate mstest
...
$ conda install -c hjkgroup molSimplify
...
$ molsimplify
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/mstest/bin/molsimplify", line 11, in <module>
    load_entry_point('molSimplify==1.2.7a0', 'console_scripts', 'molsimplify')()
  File "/usr/local/Caskroom/miniconda/base/envs/mstest/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Caskroom/miniconda/base/envs/mstest/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/Caskroom/miniconda/base/envs/mstest/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/Caskroom/miniconda/base/envs/mstest/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Caskroom/miniconda/base/envs/mstest/lib/python2.7/site-packages/molSimplify/__main__.py", line 34, in <module>
    from .Scripts.inparse import *
  File "/usr/local/Caskroom/miniconda/base/envs/mstest/lib/python2.7/site-packages/molSimplify/Scripts/inparse.py", line 15, in <module>
    import yaml
ImportError: No module named yaml
```

Running `conda install pyyaml` solves the issue, so this can probably be fixed by just including `pyyaml` in the dependencies for molSimplify.

**Comment by jpjanet** [comment]
Yes, it looks like cfff7bf57588caa6e46ed139331ba37d9f34b5d7 added yaml dependency but did not update the list of requirements. I will update the image - thanks for pointing this out!
